[QA-1507] Tolerate 404 from Google when listing project SAs
broadinstitute/gpalloc pull request #106
Opened 2021-06-17 21:52 UTC by marctalbott

Ticket: [QA-1507](https://broadworkbench.atlassian.net/browse/QA-1507)
When Google returns 404 while listing the service accounts in a project, just nuke the project from gpalloc's database since it either doesn't exist or gpalloc has somehow lost access to it

2021-06-17 21:53 UTC, marctalbott commented on src/main/scala/org/broadinstitute/dsde/workbench/gpalloc/service/GPAllocService.scala
> +  private def overPetLimitOrProjectDeleted(project: String): Future[Boolean] = {
I'd prefer to change `overPetLimit` to just list the SAs in the project and pull the logic that evaluates whether its over the limit up into this class, but I'm trying to minimize the amount of refactoring for this ticket

2021-06-17 22:05 UTC, andy7i approved these changes
nice! 👍

2021-06-21 13:42 UTC, marctalbott commented on src/main/scala/org/broadinstitute/dsde/workbench/gpalloc/service/GPAllocService.scala
> +  private def overPetLimitOrProjectDeleted(project: String): Future[Boolean] = {
Also considered renaming this to `shouldNukeProject`, but I think I prefer this naming since it describes why a project should get nuked

2021-06-21 13:44 UTC, gpolumbo-broad requested changes

2021-06-21 13:44 UTC, gpolumbo-broad commented on src/main/scala/org/broadinstitute/dsde/workbench/gpalloc/service/GPAllocService.scala
> +        logger.info(s"Could not locate $project in Google, removing it from database")
I'm not thrilled with this message being disconnected from the code that will actually try to delete.  Perhaps this wording would be better:

```suggestion
        logger.info(s"Could not locate $project in Google, it should be nuked")
```

2021-06-21 13:48 UTC, gpolumbo-broad approved these changes

2021-06-21 19:28 UTC, merged